//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.10.15 at 03:54:18 PM EEST 
//


package ua.nure.sportinventory;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for inventory complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="inventory">
 *   &lt;complexContent>
 *     &lt;extension base="{http://nure.ua/sportInventory}entity">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="originCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="concern" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="model" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="year">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;totalDigits value="4"/>
 *               &lt;minInclusive value="1900"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="gender" type="{http://nure.ua/sportInventory}gender" minOccurs="0"/>
 *         &lt;element name="size" type="{http://nure.ua/sportInventory}size" minOccurs="0"/>
 *         &lt;element name="priceInHour" type="{http://nure.ua/sportInventory}priceType" minOccurs="0"/>
 *         &lt;element name="priceInADay" type="{http://nure.ua/sportInventory}priceType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "inventory", propOrder = {
        "type",
        "originCountry",
        "concern",
        "model",
        "year",
        "gender",
        "size",
        "priceInHour",
        "priceInADay"
})
public class Inventory
        extends Entity {

    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String originCountry;
    @XmlElement(required = true)
    protected String concern;
    protected String model;
    protected int year;
    @XmlElement(defaultValue = "Any")
    @XmlSchemaType(name = "string")
    protected Gender gender;
    protected Size size;
    protected PriceType priceInHour;
    protected PriceType priceInADay;

    public Inventory() {
        gender = Gender.ANY;
    }

    /**
     * Gets the value of the type property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the originCountry property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getOriginCountry() {
        return originCountry;
    }

    /**
     * Sets the value of the originCountry property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setOriginCountry(String value) {
        this.originCountry = value;
    }

    /**
     * Gets the value of the concern property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getConcern() {
        return concern;
    }

    /**
     * Sets the value of the concern property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setConcern(String value) {
        this.concern = value;
    }

    /**
     * Gets the value of the model property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the year property.
     */
    public int getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     */
    public void setYear(int value) {
        this.year = value;
    }

    /**
     * Gets the value of the gender property.
     *
     * @return possible object is
     * {@link Gender }
     */
    public Gender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     *
     * @param value allowed object is
     *              {@link Gender }
     */
    public void setGender(Gender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the size property.
     *
     * @return possible object is
     * {@link Size }
     */
    public Size getSize() {
        return size;
    }

    /**
     * Sets the value of the size property.
     *
     * @param value allowed object is
     *              {@link Size }
     */
    public void setSize(Size value) {
        this.size = value;
    }

    /**
     * Gets the value of the priceInHour property.
     *
     * @return possible object is
     * {@link PriceType }
     */
    public PriceType getPriceInHour() {
        return priceInHour;
    }

    /**
     * Sets the value of the priceInHour property.
     *
     * @param value allowed object is
     *              {@link PriceType }
     */
    public void setPriceInHour(PriceType value) {
        this.priceInHour = value;
    }

    /**
     * Gets the value of the priceInADay property.
     *
     * @return possible object is
     * {@link PriceType }
     */
    public PriceType getPriceInADay() {
        return priceInADay;
    }

    /**
     * Sets the value of the priceInADay property.
     *
     * @param value allowed object is
     *              {@link PriceType }
     */
    public void setPriceInADay(PriceType value) {
        this.priceInADay = value;
    }

    public String toString() {
        String out = "id " + id + ": " + type + ": " + concern + " " + model + "(" + size + ")";
        return out;
    }
}
